apiVersion: apps/v1
kind: Deployment
metadata:
  name: dissco-backend-deployment
  labels:
    app: dissco-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dissco-backend
  template:
    metadata:
      labels:
        app: dissco-backend
    spec:
      containers:
        - name: dissco-backend
          image: public.ecr.aws/m8w1i6p4/dissco-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: spring.datasource.url
              value:
            - name: spring.datasource.username
              value:
            - name: spring.datasource.password
              value:
            - name: elasticsearch.hostname
              value:
            - name: elasticsearch.port
              value: 
            - name: springdoc.api-docs.path
              value: /api/v3/api-docs
            - name: springdoc.swagger-ui.path
              value: /api/swagger-ui.html
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
